### ISSUE TITLE
How to include "node_api.h"?

### ISSUE THREAD

**Issue by iamwilhelm** [canvasxyz/okra#1]
I was trying to run tests on the okra project, but ran into this issue:

```
  Error: Cannot find module '../zig-out/lib/arm64-darwin/okra.node'
  Require stack:
  - /Users/iamwil/projects/lib/okra-js/packages/okra-node/lib/index.js

  Error: Cannot find module '../zig-out/lib/arm64-darwin/okra.node'
  Require stack:
  - /Users/iamwil/projects/lib/okra-js/packages/okra-node/lib/index.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
      at Module._load (node:internal/modules/cjs/loader:985:27)
      at Module.require (node:internal/modules/cjs/loader:1235:19)
      at require (node:internal/modules/helpers:176:18)
      at file:///Users/iamwil/projects/lib/okra-js/packages/okra-node/lib/index.js:12:14
      at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
      at async run (file:///Users/iamwil/projects/lib/okra-js/node_modules/ava/lib/worker/base.js:238:3)
      at async file:///Users/iamwil/projects/lib/okra-js/node_modules/ava/lib/worker/base.js:275:2

  ✘ test/tree.test.ts exited with a non-zero exit code: 1
```

It looks like the okra-node project needs to build with zig first. So I tried:

```
➜  okra-node git:(main) zig build
install
└─ install okra-node
   └─ zig build-lib okra-node ReleaseSafe x86_64-macos 2 errors
napi/c.zig:1:20: error: C import failed
pub usingnamespace @cImport(@cInclude("node_api.h"));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/iamwil/projects/lib/okra-js/packages/okra-node/zig-cache/o/e653d7a6981f49a59e368625c60de626/cimport.h:1:10: error: 'node_api.h' file not found
#include <node_api.h>
         ^
```

It seems like I need the headers for node.js. So I installed `node_gyp`, but there's no `binding.gyp` in the repository, so I assume you linked it a different way.

How did you include `node_api.h` when building `okra-node`? Thanks.

**Comment by joeltg** [comment]
You don't need to install node-gyp, you just need to locate `node_api.h` on your system and set that path in the `build.zig` of `okra-node` https://github.com/canvasxyz/okra-js/blob/main/packages/okra-node/build.zig

Where `node_api.h` is depends on how you've installed Node. On my mac, I used the default system installer (not NVM or brew), which put it in `/usr/local/include/node`.

Just edit packages/okra-node/build.zig yourself for now. I'll add a CLI option later so that you can pass the include path in from the `zig build` command.
